config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  get "/find_comparison" => "application#find_comparison"

  get "/comparisons/:id/upvote" => "comparisons#upvote"
  get "/comparisons/:id/downvote" => "comparisons#downvote"
  get "/comparisons/top" => "comparisons#top"
  get "/comparisons/worst" => "comparisons#worst"

  get "/users/top/" => "application#top_users"
  
  devise_for :users

  get "/users/:username/" => "application#profile"




  resources :favorite_neighborhoods, only: %i[new create update edit destroy]
  resources :neighborhoods, only: %i[index show]
  resources :cities, only: %i[index show]
  resources :comments, only: %i[new create update edit destroy]
  resources :likes, only: %i[]
  resources :comparisons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comparison.rb
# == Schema Information
#
# Table name: comparisons
#
#  id                           :bigint           not null, primary key
#  body                         :string
#  built_environment_similarity :integer          default(0)
#  comments_count               :integer          default(0)
#  culinary_similarity          :integer          default(0)
#  downvotes                    :integer          default(0)
#  likes_count                  :integer          default(0)
#  net_comparison_score         :float            default(0.0)
#  net_votes                    :integer          default(0)
#  overall_similarity           :float            default(0.0)
#  people_similarity            :integer          default(0)
#  transportation_similarity    :integer          default(0)
#  upvotes                      :integer          default(0)
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  neighborhood_1_id            :integer          not null
#  neighborhood_2_id            :integer          not null
#  user_id                      :bigint           not null
#
# Indexes
#
#  index_comparisons_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Comparison < ApplicationRecord
  # belongs_to :user

  belongs_to(:user,  :required => true, :class_name => "User", :foreign_key => "user_id", :counter_cache => true )
  has_many(:likes,  :class_name => "Like", :foreign_key => "comparison_id", :dependent => :destroy )
  has_many(:comments,  :class_name => "Comment", :foreign_key => "comparison_id", :dependent => :destroy )
  belongs_to(:neighborhood_1,  :required => true, :class_name => "Neighborhood", :foreign_key => "neighborhood_1_id" )
  belongs_to(:neighborhood_2,  :required => true, :class_name => "Neighborhood", :foreign_key => "neighborhood_2_id" )

  has_many(:fans,  :through => :likes, :source => :user )
  has_one(:city_1,  :through => :neighborhood_1, :source => :city )
  has_one(:city_2,  :through => :neighborhood_2, :source => :city )


  validates :people_similarity, inclusion: { in: [0, 1, 2, 3, 4, 5], message: "select a valid similarity level"}
  validates :culinary_similarity, inclusion: { in: [0, 1, 2, 3, 4, 5], message: "select a valid similarity level"}
  validates :transportation_similarity, inclusion: { in: [0, 1, 2, 3, 4, 5], message: "select a valid similarity level"}
  validates :built_environment_similarity, inclusion: { in: [0, 1, 2, 3, 4, 5], message: "select a valid similarity level"}


  def similarity_levels_in_words
  
  end 

  validates(:user_id, :presence => true )
  validates(:neighborhood_1_id,  :presence => true, :allow_nil => false )
  validate :neighborhoods_cant_be_nil

  # validates :neighborhood_1_id, comparison: { other_than: :neighborhood_2_id }
  validate :neighborhoods_cant_match
  validate :cities_cant_match


  def neighborhoods_cant_match
    if self.neighborhood_1_id == self.neighborhood_2_id
      errors.add(:comparison, "Can't compare a neighborhoods to itself!")
    end
  end
  
  def neighborhoods_cant_be_nil
    if self.neighborhood_1_id.nil?
      errors.add(:comparison, "Must select a neighborhood 1!")
      return false
    elsif self.neighborhood_2_id.nil?
      errors.add(:comparison, "Must select a neighborhood 2!")
      return false
    else 
      return true
    end
  end

  def cities_cant_match
    if self.neighborhoods_cant_be_nil == true
      if Neighborhood.where(id: self.neighborhood_1_id).first.city_id == Neighborhood.where(id: self.neighborhood_2_id).first.city_id
        errors.add(:comparison, "Can't compare neighborhoods within the same city!")
      end
    else
    end 
  end

  validates(:neighborhood_2_id,  :presence => true )

end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  before_action :set_comparison, only: %i[ show edit update destroy upvote downvote ]

  ActiveRecord::Base.connection.tables.each do |table_name| 
    ActiveRecord::Base.connection.reset_pk_sequence!(table_name)
  end

  # GET /comparisons or /comparisons.json
  def index
    @comparisons = Comparison.includes(:user).includes(:city_1).includes(:city_2).all
    
  end

  def top
    @comparisons = Comparison.includes(:user).includes(:city_1).includes(:city_2).all.order(net_comparison_score: :desc).first(10)
    @top_three_comparisons = @comparisons.first(3)
    
  end 
  def worst
    @comparisons = Comparison.includes(:user).includes(:city_1).includes(:city_2).all.order(net_comparison_score: :asc).first(10)
  end 



  # GET /comparisons/1 or /comparisons/1.json
  def show
    
  end

  # GET /comparisons/new
  def new
    @comparison = Comparison.new
  end

  # GET /comparisons/1/edit
  def edit
    authorize @comparison

  end

  # POST /comparisons or /comparisons.json
  def create
    @comparison = Comparison.create(comparison_params)
    @comparison.user_id = current_user.id
    @comparison.upvotes = 1
    @comparison.overall_similarity = (@comparison.culinary_similarity + @comparison.transportation_similarity + @comparison.people_similarity + @comparison.built_environment_similarity)/4.0

    @comparison.net_comparison_score = @comparison.overall_similarity * @comparison.net_votes

    respond_to do |format|
      if @comparison.save
        format.html { redirect_to comparison_url(@comparison), notice: "Comparison was successfully created." }
        format.json { render :show, status: :created, location: @comparison }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comparison.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @comparison.upvotes = @comparison.upvotes + 1
    @comparison.net_votes = @comparison.upvotes - @comparison.downvotes
    @comparison.net_comparison_score = @comparison.net_votes * @comparison.overall_similarity
    @comparison.user.update(karma: Comparison.where(user: @comparison.user).order(net_comparison_score: :desc).sum(:net_comparison_score))

    respond_to do |format|
      if @comparison.save
        format.html { redirect_to comparison_url(@comparison), notice: "Upvote received." }
        format.json { render :show, status: :ok, location: @comparison }
        format.js do 
          render template: "comparisons/upvote.js.erb"
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comparison.errors, status: :unprocessable_entity }
      end
    end
  end 

  def downvote
    @comparison.downvotes = @comparison.downvotes + 1
    @comparison.net_votes = @comparison.upvotes - @comparison.downvotes
    @comparison.net_comparison_score = @comparison.net_votes * @comparison.overall_similarity
    @comparison.user.update(karma: Comparison.where(user: @comparison.user).order(net_comparison_score: :desc).sum(:net_comparison_score))

    respond_to do |format|
      if @comparison.save
        format.html { redirect_to comparison_url(@comparison), notice: "Downvote received." }
        format.json { render :show, status: :ok, location: @comparison }
        format.js do 
          render template: "comparisons/downvote.js.erb"
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comparison.errors, status: :unprocessable_entity }
      end
    end
  end 

  # PATCH/PUT /comparisons/1 or /comparisons/1.json
  def update
    authorize @comparison

    @comparison.update(comparison_params)
    @comparison.overall_similarity = (@comparison.culinary_similarity + @comparison.transportation_similarity + @comparison.people_similarity + @comparison.built_environment_similarity)/4.0

    @comparison.net_comparison_score = @comparison.overall_similarity * @comparison.net_votes

    respond_to do |format|
      if @comparison.update(comparison_params)
        format.html { redirect_to comparison_url(@comparison), notice: "Comparison was successfully updated." }
        format.json { render :show, status: :ok, location: @comparison }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comparison.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comparisons/1 or /comparisons/1.json
  def destroy
    authorize @comparison
    @comparison.destroy

    respond_to do |format|
      format.html { redirect_to comparisons_url, notice: "Comparison was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comparison
      @comparison = Comparison.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comparison_params
      params.require(:comparison).permit(:body, :user_id, :culinary_similarity, :transportation_similarity, :people_similarity, :built_environment_similarity, :overall_similarity, :neighborhood_1_id, :neighborhood_2_id, :net_comparison_score, :net_votes, :likes_count, :comments_count, :upvotes, :downvotes)
    end
end

app/helpers/comparisons_helper.rb
module ComparisonsHelper
end

app/views/comparisons/_comparison.html.erb
    <div class="mb-5 mt-5">
      <div class="card">
        <div class="p-4 pb-0 mb-0 bg-white position-relative">
          <i class="fs-1  fw-lighter"><b><%= link_to comparison.neighborhood_1.name, comparison.neighborhood_1, class: "text-reset text-decoration-none" %></b>
          <span class="position-absolute top-20 start-10 translate-middle badge rounded-pill bg-light fs-6 text-decoration-none"><%= link_to comparison.city_1.name, comparison.city_1, class: "text-decoration-none text-black-50" %></span>
          is like 
          <b><%= link_to comparison.neighborhood_2.name, comparison.neighborhood_2, class: "text-reset text-decoration-none" %></b>
          <span class="position-absolute top-5 start-10 translate-middle badge rounded-pill bg-light fs-6"><%= link_to comparison.city_2.name, comparison.city_2, class: "text-decoration-none text-black-50" %></span> because...</i>
        </div>
        <div class="card-body mt-0 pt-0">
          <p class="card-text fs-3 pt-0 mt-0 fw-light lh-sm"><%= comparison.body %>
          
          </p>
          
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-info fs-3 shadow" id="<%= dom_id(comparison) %>_net_comparison_score">
    <%= comparison.net_comparison_score %></span>
    <div class="container px-0 w-100 text-left align-items-start ">

    <div class="row ms-0 mt-5" >
          <div class="col ms-0  ps-0"> 
              
            <%= link_to "/comparisons/#{comparison.id}/upvote", remote: true, class: "btn btn-primary" do %>
              <i class="fa-solid fa-thumbs-up"></i> <span class='badge text-bg-primary' id="<%= dom_id(comparison) %>_upvotes"><%= comparison.upvotes %></span>
            <% end %> 
            <%= link_to "/comparisons/#{comparison.id}/downvote", remote: true, class: "btn btn-warning" do %>
            <i class="fa-solid fa-thumbs-down"></i> <span class='badge text-bg-warning' id="<%= dom_id(comparison) %>_downvotes"><%= comparison.downvotes %></span>
            <% end %> 
                  

            <%= link_to_unless_current "  #{comparison.comments_count}", comparison, class: 'btn btn-lg btn-outline-success fw-light fa-regular fa-comments text-opacity-50' do %>
            <% link_to "" %> 
            <% end %>
          </div>
          
          <div class="col me-0 pe-0 text-end">
            <span class="fw-light opacity-50 fs-4">
                <span class="fw-lighter opacity-50"><i class="fa-solid fa-people-group"></i> <%= comparison.people_similarity %> 
                <i class="fa-solid fa-utensils ms-4"></i> <%= comparison.culinary_similarity %>
                <i class="fa-solid fa-train ms-4"></i> <%= comparison.transportation_similarity %>
                <i class="fa-solid fa-tree-city ms-4"></i> <%= comparison.built_environment_similarity %>
                <i class="fa-solid fa-arrow-right ms-4"></i>
              </span><span class="ms-4">Overall: <%= comparison.overall_similarity %></span></span>
          </div>
          </div>
      </div>
      </div>
      <div class="card-footer text-muted text-end fs-6">
        Submitted <%= time_ago_in_words(comparison.created_at) %> ago by <%= link_to "#{comparison.user.username}", "/users/#{comparison.user.username}" %> 
        <% if current_user == nil %>

        <% elsif comparison.user.username %> 
          | <%= link_to 'Edit', edit_comparison_path(comparison) %> |
          <%= link_to 'Delete', comparison, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% else %>
 
        <% end%>
        </div>
      </div>
    </div>

app/views/comparisons/_form.html.erb
<%= form_with(model: comparison) do |form| %>
  <% if comparison.errors.any? %>
    <div id="error_explanation">
    <div class="alert">
      <h2><%= pluralize(comparison.errors.count, "error") %> prohibited this comparison from being saved:</h2>

      <ul>
        <% comparison.errors.each do |error| %> 
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
    </div>
  <% end %>
  
  <div>
    <%= form.label "Pick a first neighborhood", class: "fs-2" %>
    <br>
    <%= form.collection_select :neighborhood_1_id, Neighborhood.order(:city_id).order(:name),:id,:name_with_city, class: "form-select-lg form-floating w-50 fs-3", include_blank:true  %>
  </div>
<div class="form-label fs-2 ">which is comparable to...</div>
  <div class="">
    <%= form.collection_select :neighborhood_2_id, Neighborhood.order(:city_id).order(:name),:id,:name_with_city, class: "form-select-xlg form-floating w-50", include_blank:true %><br>
        <%= form.label "(hint: this is any neighborhood in another city)", class: "form-label fw-lighter" %>

  </div>
  <div class="field mb-4">
    <div class="form-label fs-2">because...</div>
    <%= form.text_area :body, class: "form-control" %>
    <div class="form-label fw-lighter">(hint: the more descriptive and specific comparisons get more upvotes)</div>
  </div>
  <div class="field">
    <%= form.hidden_field :user_id %>

  </div>
<div class="fs-3">Think about the components of the neighborhoods, how similar are they?</div>
    <div class="form-label fw-lighter mb-4">(hint: 0 not similar at all, 5 almost identical)</div>

  <div class="field">
    <i class="fa-solid fa-utensils mx-4"></i>
    <%= form.label :culinary_similarity, class: "form-label" %>
    <%= form.select :culinary_similarity, ['0','1','2','3','4','5'] %>
  </div>

  <div class="field">
    <i class="fa-solid fa-train mx-4"></i>
    <%= form.label :transportation_similarity, class: "form-label" %>
    <%= form.select :transportation_similarity, ['0','1','2','3','4','5'] %>
  </div>
  <div class="field">
    <i class="fa-solid fa-tree-city mx-4"></i>
    <%= form.label :built_environment_similarity, class: "form-label" %>
    <%= form.select :built_environment_similarity, ['0','1','2','3','4','5'] %>
  </div>
  <div class="field">
    <i class="fa-solid fa-people-group mx-4"></i>
    <%= form.label :people_similarity, class: "form-label" %>
    <%= form.select :people_similarity, ['0','1','2','3','4','5'] %>
  </div>


  <div class="actions mb-4">
    <%= form.submit class: "btn btn-primary mt-4" %>
  </div>
  </div>
<% end %>

app/views/comparisons/_new.html.erb
<h1 class="mb-4">Create a new comparison</h1>
<div class="row w-50">
<%= render 'form', comparison: @comparison %>
</div>
<div class="row">
<%= link_to 'Back', comparisons_path %>

app/views/comparisons/downvote.js.erb
console.log("downvoting!")
console.log("<%= dom_id(@comparison) %>_downvotes")
var updated_downvote = $("<span class='badge text-bg-light' id='<%= dom_id(@comparison) %>_downvotes'><%= @comparison.downvotes %></span>");
var updated_net_comparison_score = $("<span class='position-absolute top-0 start-100 translate-middle badge rounded-pill bg-info fs-3 shadow' id='<%= dom_id(@comparison) %>_net_comparison_score'><%= @comparison.net_comparison_score %></span>");
updated_downvote.hide();
updated_net_comparison_score.hide();

$("#<%= dom_id(@comparison) %>_downvotes").replaceWith(updated_downvote);
$("#<%= dom_id(@comparison) %>_net_comparison_score").replaceWith(updated_net_comparison_score);

updated_downvote.fadeIn();
updated_net_comparison_score.fadeIn();

app/views/comparisons/edit.html.erb
<h1>Editing Comparison</h1>

<%= render 'form', comparison: @comparison %>

<%= link_to 'Show', @comparison %> |
<%= link_to 'Back', comparisons_path %>

app/views/comparisons/index.html.erb
  <% content_for :title, "Most recent comparisons" %>


<div class="hstack gap-3">
<div><h1 class="fs-1 fw-lighter">Most recent comparisons</h1></div>

</div>

<% @comparisons.order(created_at: :desc).each do |comparison| %>
 <%= render 'comparisons/comparison', comparison: comparison  %>
<% end %>


<%= link_to 'New Comparison', new_comparison_path %>

app/views/comparisons/new.html.erb
  <% content_for :title, "New comparison" %>

<h1 class="mb-4">Create a new comparison</h1>
<div class="row w-50">
<%= render 'form', comparison: @comparison %>
</div> 
<div class="row">
<%= link_to 'Back', comparisons_path %>

app/views/comparisons/show.html.erb
 <%= render 'comparisons/comparison', comparison: @comparison  %>

  <% content_for :title, @comparison.neighborhood_1.name + " is like " + @comparison.neighborhood_2.name %>

<div class="h5">Comments:</div>

<ul class="list-group list-group-flush" >
<li id="<%= dom_id(@comparison.comments.build) %>_form" class="list-group-item">
 <%= render 'comments/form', comparison: @comparison, comment: @comparison.comments.build  %></li>

<% @comparison.comments.includes(:commenter).all.order(created_at: :desc).each do |comment| %>
 <%= render 'comments/comment', comment: comment  %>

    <% end %>
  </ul> 


<div class="row"><%= link_to 'Back', comparisons_path %></div>

app/views/comparisons/top.html.erb
  <% content_for :title, "Top comparisons all time" %>


<div class="hstack gap-3">
<div><h1 class="fs-1 fw-lighter"><b><i>Top</i></b> Comparisons All time</h1></div>

</div>
<ol>
<% @comparisons.each do |comparison| %>
 <li class="fs-1"><%= render 'comparisons/comparison', comparison: comparison  %></li>
<% end %>
</ol>

<%= link_to 'New Comparison', new_comparison_path %>

app/views/comparisons/upvote.js.erb
console.log("upvoting!")
console.log("<%= dom_id(@comparison) %>_upvotes")
var updated_upvote = $("<span class='badge text-bg-primary' id='<%= dom_id(@comparison) %>_upvotes'><%= @comparison.upvotes %></span>");

$("#<%= dom_id(@comparison) %>_upvotes").replaceWith(updated_upvote);

app/views/comparisons/worst.html.erb
  <% content_for :title, "Worst comparisons all time" %>

<div class="hstack gap-3">
<div><h1 class="fs-1 fw-lighter"><b><i>Worst</i></b> Comparisons All time</h1></div>

</div>
<ol>
<% @comparisons.each do |comparison| %>
 <li class="fs-1"><%= render 'comparisons/comparison', comparison: comparison  %></li>
<% end %>
</ol>

<%= link_to 'New Comparison', new_comparison_path %>