config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  get "/find_comparison" => "application#find_comparison"

  get "/comparisons/:id/upvote" => "comparisons#upvote"
  get "/comparisons/:id/downvote" => "comparisons#downvote"
  get "/comparisons/top" => "comparisons#top"
  get "/comparisons/worst" => "comparisons#worst"

  get "/users/top/" => "application#top_users"
  
  devise_for :users

  get "/users/:username/" => "application#profile"




  resources :favorite_neighborhoods, only: %i[new create update edit destroy]
  resources :neighborhoods, only: %i[index show]
  resources :cities, only: %i[index show]
  resources :comments, only: %i[new create update edit destroy]
  resources :likes, only: %i[]
  resources :comparisons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite_neighborhood.rb
# == Schema Information
#
# Table name: favorite_neighborhoods
#
#  id              :bigint           not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  neighborhood_id :bigint           not null
#  user_id         :bigint           not null
#
# Indexes
#
#  index_favorite_neighborhoods_on_neighborhood_id  (neighborhood_id)
#  index_favorite_neighborhoods_on_user_id          (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (neighborhood_id => neighborhoods.id)
#  fk_rails_...  (user_id => users.id)
#
class FavoriteNeighborhood < ApplicationRecord


  belongs_to(:user,  :required => true, :class_name => "User", :foreign_key => "user_id", :counter_cache => true )
  belongs_to(:neighborhood,  :required => true, :class_name => "Neighborhood", :foreign_key => "neighborhood_id", :counter_cache => true )

  # has_one(:neighborhood_name,  :through => :neighborhood_id )


end

app/controllers/favorite_neighborhoods_controller.rb
class FavoriteNeighborhoodsController < ApplicationController
  before_action :set_favorite_neighborhood, only: %i[ show edit update destroy ]
  before_action :set_user

  # GET /favorite_neighborhoods or /favorite_neighborhoods.json
  def index
    @favorite_neighborhoods = FavoriteNeighborhood.all
  end

  # GET /favorite_neighborhoods/1 or /favorite_neighborhoods/1.json
  def show
  end

  # GET /favorite_neighborhoods/new
  def new
    @favorite_neighborhood = FavoriteNeighborhood.new
  end

  # GET /favorite_neighborhoods/1/edit
  def edit
  end

  # POST /favorite_neighborhoods or /favorite_neighborhoods.json
  def create
    @favorite_neighborhood = FavoriteNeighborhood.new(favorite_neighborhood_params)

    respond_to do |format|
      if @favorite_neighborhood.save
        format.html { redirect_to neighborhood_url(@favorite_neighborhood.neighborhood), notice: "Favorite neighborhood was successfully created." }
        format.json { render :show, status: :created, location: @favorite_neighborhood }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favorite_neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorite_neighborhoods/1 or /favorite_neighborhoods/1.json
  def update
    respond_to do |format|
      if @favorite_neighborhood.update(favorite_neighborhood_params)
        format.html { redirect_to favorite_neighborhood_url(@favorite_neighborhood), notice: "Favorite neighborhood was successfully updated." }
        format.json { render :show, status: :ok, location: @favorite_neighborhood }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favorite_neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_neighborhoods/1 or /favorite_neighborhoods/1.json
  def destroy
    @old_neighborhood = @favorite_neighborhood
    @favorite_neighborhood.destroy

    respond_to do |format|
      format.html { redirect_to neighborhood_url(@old_neighborhood.neighborhood), notice: "Favorite neighborhood was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_neighborhood
      @favorite_neighborhood = FavoriteNeighborhood.find(params[:id])
    end

    def set_user

    end

    # Only allow a list of trusted parameters through.
    def favorite_neighborhood_params
      params.require(:favorite_neighborhood).permit(:user_id, :neighborhood_id)
    end
end

app/helpers/favorite_neighborhoods_helper.rb
module FavoriteNeighborhoodsHelper
end

app/views/favorite_neighborhoods/_form.html.erb
<%= form_with(model: favorite_neighborhood) do |form| %>
  <% if favorite_neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite_neighborhood.errors.count, "error") %> prohibited this favorite_neighborhood from being saved:</h2>

      <ul>
        <% favorite_neighborhood.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% if FavoriteNeighborhood.where(user_id: current_user.id).where(neighborhood_id: @neighborhood.id) == [] %>


  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.hidden_field :neighborhood_id, value: @neighborhood.id %>
  </div>

  <div class="actions">
    <%= form.button type: :submit, class: "btn btn-link" do %>
      <i class="fa-regular fa-heart"></i>
    <% end %>
  </div>
  <% else %>
  <% @favorite_neighborhood = FavoriteNeighborhood.where(user_id: current_user.id).where(neighborhood_id: @neighborhood.id).first %>
  <%= link_to favorite_neighborhood_path(@favorite_neighborhood.id), method: :delete do %>
  <i class="fa-solid fa-heart"></i>
  <% end %>
  <% end %>
<% end %>

app/views/favorite_neighborhoods/edit.html.erb
<h1>Editing Favorite Neighborhood</h1>

<%= render 'form', favorite_neighborhood: @favorite_neighborhood %>

<%= link_to 'Show', @favorite_neighborhood %> |
<%= link_to 'Back', favorite_neighborhoods_path %>

app/views/favorite_neighborhoods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorite Neighborhoods</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Neighborhood</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorite_neighborhoods.each do |favorite_neighborhood| %>
      <tr>
        <td><%= favorite_neighborhood.user_id %></td>
        <td><%= favorite_neighborhood.neighborhood_id %></td>
        <td><%= link_to 'Show', favorite_neighborhood %></td>
        <td><%= link_to 'Edit', edit_favorite_neighborhood_path(favorite_neighborhood) %></td>
        <td><%= link_to 'Destroy', favorite_neighborhood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite Neighborhood', new_favorite_neighborhood_path %>

app/views/favorite_neighborhoods/new.html.erb
<h1>New Favorite Neighborhood</h1>

<%= render 'form', favorite_neighborhood: @favorite_neighborhood %>

<%= link_to 'Back', favorite_neighborhoods_path %>

app/views/favorite_neighborhoods/show.html.erb
<p>
  <strong>User:</strong>
  <%= @favorite_neighborhood.user_id %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @favorite_neighborhood.neighborhood_id %>
</p>

<%= link_to 'Edit', edit_favorite_neighborhood_path(@favorite_neighborhood) %> |
<%= link_to 'Back', favorite_neighborhoods_path %>