config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  get "/find_comparison" => "application#find_comparison"

  get "/comparisons/:id/upvote" => "comparisons#upvote"
  get "/comparisons/:id/downvote" => "comparisons#downvote"
  get "/comparisons/top" => "comparisons#top"
  get "/comparisons/worst" => "comparisons#worst"

  get "/users/top/" => "application#top_users"
  
  devise_for :users

  get "/users/:username/" => "application#profile"




  resources :favorite_neighborhoods, only: %i[new create update edit destroy]
  resources :neighborhoods, only: %i[index show]
  resources :cities, only: %i[index show]
  resources :comments, only: %i[new create update edit destroy]
  resources :likes, only: %i[]
  resources :comparisons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_add_comparison_button.html.erb
        <% if user_signed_in? %>


<button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#add_comparison">
  Add your own comparison! 
</button>
<div class="modal fade" id="add_comparison" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content text-start">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Add a new comparison</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'comparisons/form', comparison: Comparison.new %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
<% else %>
<button type="button" class="btn btn-secondary" disabled>
  Add your own comparison! 
</button>
<% end %>

app/views/shared/_cdns.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/d945962b0a.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>

app/views/shared/_map.html.erb
<script>
  function initMap() {
    var mapDiv = document.getElementById('map');
    

    var map = new google.maps.Map(mapDiv);

    var bounds = new google.maps.LatLngBounds();
    
    var infowindow = new google.maps.InfoWindow({
      content: "<%= place.name %> " 
    });
    
    var marker = new google.maps.Marker({
      position: {lat: <%= lat %>, lng: <%= lng %>}, 
      map: map,
      title: '<%= place.name %>)',
      icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png' 
    });
    
    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });

  bounds.extend(new google.maps.LatLng(<%= lat %>, <%= lng %>));
  map.fitBounds(bounds);
  var listener = google.maps.event.addListener(map, "idle", function() { 
  if (map.getZoom() > 16) map.setZoom(13); 
  google.maps.event.removeListener(listener); 
});
  };
  
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV.fetch("GMAPS_KEY") %>&callback=initMap"
async defer></script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light mb-4">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
    <i class="fa-solid fa-right-left"></i> <span class="fs-3 fw-light ms-2">Comparison</span> 
    <% end %>
    <div class="vr me-4"></div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto ">
        <li class="nav-item">
          <span class="nav-link"><%= link_to "Home", "/", class: "nav-link" %></span>
        </li>
         <li class="nav-item dropdown mt-2">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Explore Places
          </a>
          <ul class="dropdown-menu">
            <li><span class="nav-link"><%= link_to_unless_current "Cities", cities_path, class: "nav-link" %></span></li>
            <li><span class="nav-link"><%= link_to_unless_current "Neighborhoods", neighborhoods_path, class: "nav-link" %></span></li>
          </ul>
        </li>

         <li class="nav-item dropdown mt-2">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Comparisons
          </a>
          <ul class="dropdown-menu">
            <li><span class="nav-link"><%= link_to_unless_current "Recent Comparisons", comparisons_path, class: "nav-link" %></span>
</li>
            <li><span class="nav-link"><%= link_to_unless_current "Top Comparisons", comparisons_top_path, class: "nav-link" %></span></li>
            <li>                            <span class="nav-link"><%= link_to_unless_current "Worst Comparisons", comparisons_worst_path, class: "nav-link" %></span>
</li>
          </ul>
        </li>


                <li class="nav-item">
                            <span class="nav-link"><%= link_to "Top Contributors", users_top_path, class: "nav-link" %></span>

        </li>

        <li class="nav-item mt-2">
<%= render 'shared/add_comparison_button', comparison: Comparison.new %>


        </li>

      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "#{current_user.username.capitalize}'s Profile", "/users/#{current_user.username}", class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
        <% end %>
      </ul>


    </div>
  </div>
</nav>

app/views/shared/_top_comparisons_gallery.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
  <div class="col">
    <div class="carousel-item active" data-bs-interval="4000">
      <div class="d-block w-50 mx-auto" >
            <%= render "comparisons/comparison", comparison: @top_three_comparisons[0]  %>
      </div>

    </div>
    <div class="carousel-item" data-bs-interval="2000">
        <div class="d-block w-50 mx-auto" >
            <%= render "comparisons/comparison", comparison: @top_three_comparisons[1]  %>
      </div>
    </div>
    <div class="carousel-item">
      <    <div class="d-block w-50 mx-auto" >
            <%= render "comparisons/comparison", comparison: @top_three_comparisons[2]  %>
      </div>
    </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>